#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-lintr
Version  : 2.0.1
Release  : 24
URL      : https://cran.r-project.org/src/contrib/lintr_2.0.1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/lintr_2.0.1.tar.gz
Summary  : A 'Linter' for R Code
Group    : Development/Tools
License  : MIT
Requires: R-crayon
Requires: R-cyclocomp
Requires: R-digest
Requires: R-httr
Requires: R-jsonlite
Requires: R-knitr
Requires: R-rex
Requires: R-rstudioapi
Requires: R-testthat
Requires: R-xml2
Requires: R-xmlparsedata
BuildRequires : R-crayon
BuildRequires : R-cyclocomp
BuildRequires : R-digest
BuildRequires : R-httr
BuildRequires : R-jsonlite
BuildRequires : R-knitr
BuildRequires : R-rex
BuildRequires : R-rstudioapi
BuildRequires : R-testthat
BuildRequires : R-xml2
BuildRequires : R-xmlparsedata
BuildRequires : buildreq-R

%description
semantic issues.  Supports on the fly checking of R code edited with 'RStudio IDE', 'Emacs',
    'Vim', 'Sublime Text' and 'Atom'.

%prep
%setup -q -c -n lintr
cd %{_builddir}/lintr

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1589827604

%install
export SOURCE_DATE_EPOCH=1589827604
rm -rf %{buildroot}
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lintr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lintr
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library lintr
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc lintr || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/lintr/DESCRIPTION
/usr/lib64/R/library/lintr/INDEX
/usr/lib64/R/library/lintr/LICENSE
/usr/lib64/R/library/lintr/Meta/Rd.rds
/usr/lib64/R/library/lintr/Meta/features.rds
/usr/lib64/R/library/lintr/Meta/hsearch.rds
/usr/lib64/R/library/lintr/Meta/links.rds
/usr/lib64/R/library/lintr/Meta/nsInfo.rds
/usr/lib64/R/library/lintr/Meta/package.rds
/usr/lib64/R/library/lintr/Meta/vignette.rds
/usr/lib64/R/library/lintr/NAMESPACE
/usr/lib64/R/library/lintr/NEWS.md
/usr/lib64/R/library/lintr/R/lintr
/usr/lib64/R/library/lintr/R/lintr.rdb
/usr/lib64/R/library/lintr/R/lintr.rdx
/usr/lib64/R/library/lintr/doc/creating_linters.Rmd
/usr/lib64/R/library/lintr/doc/creating_linters.html
/usr/lib64/R/library/lintr/doc/index.html
/usr/lib64/R/library/lintr/example/bad.R
/usr/lib64/R/library/lintr/example/complexity.R
/usr/lib64/R/library/lintr/help/AnIndex
/usr/lib64/R/library/lintr/help/aliases.rds
/usr/lib64/R/library/lintr/help/lintr.rdb
/usr/lib64/R/library/lintr/help/lintr.rdx
/usr/lib64/R/library/lintr/help/paths.rds
/usr/lib64/R/library/lintr/html/00Index.html
/usr/lib64/R/library/lintr/html/R.css
/usr/lib64/R/library/lintr/rstudio/addins.dcf
/usr/lib64/R/library/lintr/syntastic/lintr.vim
/usr/lib64/R/library/lintr/tests/testthat.R
/usr/lib64/R/library/lintr/tests/testthat/checkstyle.xml
/usr/lib64/R/library/lintr/tests/testthat/default_linter_testcode.R
/usr/lib64/R/library/lintr/tests/testthat/exclusions-test
/usr/lib64/R/library/lintr/tests/testthat/helper.R
/usr/lib64/R/library/lintr/tests/testthat/knitr_formats/test.Rhtml
/usr/lib64/R/library/lintr/tests/testthat/knitr_formats/test.Rmd
/usr/lib64/R/library/lintr/tests/testthat/knitr_formats/test.Rnw
/usr/lib64/R/library/lintr/tests/testthat/knitr_formats/test.Rrst
/usr/lib64/R/library/lintr/tests/testthat/knitr_formats/test.Rtex
/usr/lib64/R/library/lintr/tests/testthat/knitr_formats/test.Rtxt
/usr/lib64/R/library/lintr/tests/testthat/lints
/usr/lib64/R/library/lintr/tests/testthat/test-T_and_F_symbol_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-absolute_path_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-assignment_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-cache.R
/usr/lib64/R/library/lintr/tests/testthat/test-checkstyle_output.R
/usr/lib64/R/library/lintr/tests/testthat/test-closed_curly_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-commas_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-commented_code_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-comments.R
/usr/lib64/R/library/lintr/tests/testthat/test-cyclocomp_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-defaults.R
/usr/lib64/R/library/lintr/tests/testthat/test-deprecated.R
/usr/lib64/R/library/lintr/tests/testthat/test-equals_na_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-error.R
/usr/lib64/R/library/lintr/tests/testthat/test-exclusions.R
/usr/lib64/R/library/lintr/tests/testthat/test-expect_lint.R
/usr/lib64/R/library/lintr/tests/testthat/test-extraction_operator_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-function_left_parentheses_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-get_source_expressions.R
/usr/lib64/R/library/lintr/tests/testthat/test-implicit_integer_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-infix_spaces_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-knitr_formats.R
/usr/lib64/R/library/lintr/tests/testthat/test-line_length_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-methods.R
/usr/lib64/R/library/lintr/tests/testthat/test-no_tab_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-nonportable_path_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-object_length_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-object_name_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-object_usage_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-open_curly_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-paren_brace_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-pipe_continuation_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-rstudio_markers.R
/usr/lib64/R/library/lintr/tests/testthat/test-semicolon_terminator_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-seq_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-settings.R
/usr/lib64/R/library/lintr/tests/testthat/test-single_quotes_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-spaces_inside_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-spaces_left_parentheses_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-todo_comment_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-trailing_blank_lines_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-trailing_whitespace_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-undesirable_function_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-undesirable_operator_linter.R
/usr/lib64/R/library/lintr/tests/testthat/test-unneeded_concatenation_linter.R
